# Generated by Django 5.1.6 on 2025-04-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
